theme = "harbor"
baseurl = "https://fukucchi.github.io/blog/"
title = "エンジニアにたどりつくまで"
# パスの指定。これをしないとcssがうまく反映されません。
canonifyurls = true
paginate = 6
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir = "docs"

# Optional
# If you use googleAnalytics, you set top-level options in config.toml to the beginning of the config file like other top-level options.
googleAnalytics = "UA-172996963-1"
# and disqus too.
disqusShortName = "yourdisqusshortname"

[Author]
  name = "Fukucchi"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3


# [[params.nav]]
#  identifier = "search"
#  name = "Search"
#  icon = "fas fa-search fa-lg"
#  url = "search"
#  weight = 3

[params.logo]
  url = "home.png" # static/images/icon.png
  width = 40
  height = 40
  alt = "Logo"

  [params]
  description = "Text about my cool site"
  images = ["home.png"]
